spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: Ducvc123123!@#$%
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect


server:
  port: 9595